language: cpp

sudo: false

os:
  - linux

compiler:
  - g++-4.9

script:
  - make CXX=g++-4.9 test

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
