language: cpp

sudo: false

os:
  - linux

env:
  matrix:
    - CXX_STD=c++98 BUILD_TYPE=Release
    - CXX_STD=c++11 BUILD_TYPE=Release
    - CXX_STD=c++98 BUILD_TYPE=Debug
    - CXX_STD=c++11 BUILD_TYPE=Debug

compiler:
  - g++-5
  - clang++

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCXX_STD=$CXX_STD ..
  - make testall

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - clang

